name: Backend CI/CD

on:
  workflow_dispatch:    # 수동 트리거
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Run tests
        run: ./gradlew test

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: fmrs-backend-jar
          path: build/libs/*.jar

  deploy:
    needs: build-and-deploy
    runs-on: ubuntu-latest

    steps:
      - name: Download built JAR
        uses: actions/download-artifact@v4
        with:
          name: fmrs-backend-jar

      - name: Copy JAR to EC2
        uses: appleboy/scp-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: '*.jar'
          target: /opt/fmrs/fmrs-0.0.1-SNAPSHOT.jar

      - name: Restart fmrs.service on EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo systemctl daemon-reload
            sudo systemctl restart fmrs
